apiVersion: v1
kind: Service
metadata:
  name: adguard-exporter
  namespace: adguard
  labels:
    app: adguard-exporter
spec:
  ports:
    - name: adguard-exp
      port: 9618
  selector:
    app: adguard-exporter
  clusterIP: None
