apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: adguard
  labels:
    app: adguard
spec:
  ports:
    - name: http-initial
      port: 3000
    - name: http
      port: 80
  selector:
    app: adguard
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-lb
  namespace: adguard
  annotations:
    metallb.universe.tf/address-pool: adguard-pool
spec:
  type: LoadBalancer
  ports:
  # - name: http-initial
  #   port: 3000
  #   protocol: TCP
  #   targetPort: 3000
  # - name: http
  #   port: 80
  #   protocol: TCP
  #   targetPort: 80
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: adguard
