apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pv-claim
  namespace: adguard
  labels:
    app: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi